[package]
name = "CosmosCodeWorkspace"
version = "0.1.0"
edition = "2021"
[dependencies]
# List dependencies required by your workspace projects

[dependencies]
tokio = "1"
serde = "1"
serde_json = "1"
rust-cpython = "0.8"
qiskit = "0.21"