# f:\CosmosCode\wireguard-config-manager\Cargo.toml
[package]
name = "wireguard-config-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
# ... your dependencies ...

# This would be the duplicate causing the error if it's at line 11
[package] 
# ... more package stuff ...
