# f:\CosmosCode\wireguard-config-manager\Cargo.toml
[package]
name = "wireguard-config-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
